# Generated by Django 3.2.10 on 2023-07-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=50, verbose_name='장소명')),
                ('image', models.ImageField(upload_to='', verbose_name='추천 장소 이미지')),
                ('region', models.CharField(max_length=20, null=True, verbose_name='구')),
                ('tag', models.CharField(max_length=50, null=True, verbose_name='태그')),
                ('content', models.TextField(verbose_name='장소에 대한 설명')),
                ('tip', models.TextField(verbose_name='이렇게 활용하세요!')),
            ],
        ),
    ]
